collections:
  tags:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

